name: passing variables

on: 
  workflow_dispatch:

jobs:

  producer:
    runs-on: ubuntu-24.04
    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - name: Generate and export foo
        id: generate-foo
        run: |
          foo=bar
          
          # 1) step output (for job output)
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"

          # 2) job scoped envioronment variable
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: Inspect values inside producer
        run: |

          echo "FOO (set via GITHUB_ENV):$FOO"
          echo "foo (set via step output):${{ steps.generate-foo.outputs.foo }}"